#!/usr/bin/env bash

# Login and configure connection to IBM Cloud COS.
ibmcloud login --apikey "${IBMCLOUD_API_KEY}" --no-region;
ibmcloud cos config crn --crn "${IBMCLOUD_STORAGE_CRN}";
ibmcloud cos config region --region ${IBMCLOUD_BUCKET_REGION};

# Upload build directory contents to the bucket.
for file in `find build/* -type f`
do
  echo "Uploading file... ${file}"
  ibmcloud cos upload --bucket ${IBMCLOUD_BUCKET} --key ${file} --file ${file};
done
