language: node_js
node_js: lts/*
dist: focal
cache: yarn

notifications:
  email: false

install:
  - yarn install
  - ./scripts/compile-all.sh
  # Make sure the file exists, and it's valid JSON.
  - stat ./src/.jest-test-results.json >/dev/null 2>&1 || echo '{}' > ./src/.jest-test-results.json

stages:
  - name: test
  - name: deploy-main
    if: branch IN (main) AND type IN (push) AND fork = false
  - name: deploy-development
    if: branch IN (development) AND type IN (push) AND fork = false
  - name: publish
    if: branch IN (main) AND type IN (push) AND fork = false

env:
  global:
    - HUSKY_SKIP_INSTALL=1

custom:
  before_install: &cos_before_install
    - for i in {1..5}; do curl -fsSL https://clis.cloud.ibm.com/install/linux | sh && break || sleep 2; done
    - for i in {1..5}; do ibmcloud plugin install cloud-object-storage && break || sleep 2; done
  script: &cos_script
    - mkdir -p "${TRAVIS_BUILD_DIR}/widget-registry"
    - yarn storybook:build --output-dir "${TRAVIS_BUILD_DIR}/catalog/storybook"
    - npx @js-widgets/webpack-cli --existing-registry="${PUBLIC_URL}/registry.json" --output-dir="${TRAVIS_BUILD_DIR}/widget-registry" "${TRAVIS_BUILD_DIR}"
  deploy: &cos_deploy
    provider: script
    script: |
      ./scripts/ci/upload-widgets-to-cos.sh
      ./scripts/ci/upload-public-dirs-to-cos.sh
      ./scripts/ci/upload-translations-to-cos.sh
      ./scripts/ci/upload-catalog-to-cos.sh
    skip_cleanup: true
    on:
      all_branches: true
jobs:
  include:
    - stage: test
      script:
        - yarn lint:ci
        - yarn test:ci

    - stage: deploy-main
      env:
        - IBMCLOUD_COS_BUCKET=hybrid-cloud-widgets-production
        - IBMCLOUD_COS_REGION=us-geo
        - PUBLIC_URL="https://hybrid-cloud-widgets-production.s3.us.cloud-object-storage.appdomain.cloud"
        - PUBLIC_ASSETS_URL="https://hybrid-cloud-widgets-production.s3.us.cloud-object-storage.appdomain.cloud/static"
        - NODE_ENV=production
      before_install: *cos_before_install
      script: *cos_script
      deploy: *cos_deploy
    - stage: deploy-development
      env:
        - IBMCLOUD_COS_BUCKET=hybrid-cloud-widgets-development
        - IBMCLOUD_COS_REGION=us-geo
        - PUBLIC_URL="https://hybrid-cloud-widgets-development.s3.us.cloud-object-storage.appdomain.cloud"
        - PUBLIC_ASSETS_URL="https://hybrid-cloud-widgets-development.s3.us.cloud-object-storage.appdomain.cloud/static"
        - NODE_ENV=production
      before_install: *cos_before_install
      script: *cos_script
      deploy: *cos_deploy

    - stage: publish
      script:
        - yarn storybook:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        github_url: github.ibm.com
        keep_history: false
        allow_empty_commit: true
        local_dir: dist
        verbose: true
        on:
          all_branches: true
