language: node_js
node_js: lts/*
dist: focal
cache: yarn

notifications:
  email: false

install:
  - yarn install
  # Make sure the file exists, and it's valid JSON.
  - stat ./src/.jest-test-results.json >/dev/null 2>&1 || echo '{}' > ./src/.jest-test-results.json

stages:
  - name: test
  - name: deploy-main
    if: branch IN (main) AND type IN (push) AND fork = false
  - name: deploy-development
    if: branch IN (development) AND type IN (push) AND fork = false
  - name: publish
    if: branch IN (main) AND type IN (push) AND fork = false

env:
  global:
    - HUSKY_SKIP_INSTALL=1
jobs:
  include:
    - stage: test
      script:
        - yarn lint:ci
        - yarn test:ci

    - stage: deploy-main
      env:
        - IBMCLOUD_COS_BUCKET=hybrid-cloud-widgets-production
        - NODE_ENV=production
      before_install:
        - for i in {1..5}; do curl -fsSL https://clis.cloud.ibm.com/install/linux | sh && break || sleep 2; done
        - for i in {1..5}; do ibmcloud plugin install cloud-object-storage && break || sleep 2; done
      script:
        - yarn storybook:build --output-dir "${TRAVIS_BUILD_DIR}/widget-registry"
        - npx @js-widgets/webpack-cli --existing-registry="https://${IBMCLOUD_COS_BUCKET}.s3.us.cloud-object-storage.appdomain.cloud/registry.json" --output-dir="${TRAVIS_BUILD_DIR}/widget-registry" "${TRAVIS_BUILD_DIR}"
      deploy:
        provider: script
        script: ./scripts/ci/upload-to-cos.sh ${TRAVIS_BUILD_DIR}/widget-registry
        skip_cleanup: true
        on:
          all_branches: true
    - stage: deploy-development
      env:
        - IBMCLOUD_COS_BUCKET=hybrid-cloud-widgets-development
        - NODE_ENV=production

    - stage: publish
      script:
        - yarn storybook:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        github_url: github.ibm.com
        keep_history: true
        allow_empty_commit: true
        local_dir: dist
        verbose: true
        on:
          all_branches: true
