services:
  mysql:
    image: tugboatqa/mariadb
    commands:
      ready:
        - mysqladmin ping

      init:
        - mkdir -p /etc/service/mysql
        - echo "#!/bin/sh" > /etc/service/mysql/run
        - echo "mysql -e 'SET GLOBAL max_allowed_packet=134217728'" >> /etc/service/mysql/run
        - chmod +x /etc/service/mysql/run

      build:
        - mysql -e 'SET GLOBAL max_allowed_packet=134217728'
  storybook:
    default: true
    image: tugboatqa/httpd
    commands:
      init: |
        set -eux
        curl -sL https://deb.nodesource.com/setup_16.x | sh
        apt-get install -y nodejs
        npm install --global yarn
        ln --symbolic --no-dereference --force "${TUGBOAT_ROOT}/dist/storybook" "${DOCROOT}"
      build: |
        yarn install
        yarn compile
        rm --recursive --force ./dist
        cat "${TUGBOAT_ROOT}/.tugboat/.env.local" >> "${TUGBOAT_ROOT}/.env"
        yarn storybook:build --debug-webpack
        cd "${TUGBOAT_ROOT}/adr-docs"
        yarn install && yarn build --prefix-paths
        cd "${TUGBOAT_ROOT}"
        ln --symbolic --no-dereference --force "${TUGBOAT_ROOT}/adr-docs/public" "${TUGBOAT_ROOT}/dist/storybook/architecture"

    screenshot:
      enabled: true
      waitUntil:
        - networkidle0

    visualdiff:
      enabled: true

    lighthouse:
      enabled: true
      screen:
        - desktop
      config:
        extends: lighthouse:default
        settings:
          onlyCategories:
            - performance
            - accessibility
            - best-practices

    urls:
      interactive-integration-walkthrough:
        - /iframe.html?id=widgets-interactive-integration-walkthrough-components--default&args=&globals=locale:en&viewMode=story
      journey-ai:
        - /iframe.html?id=widgets-journey-to-ai-components--default&args=&globals=locale:en&viewMode=story
      product-explorer:
        - /iframe.html?id=widgets-product-explorer-components--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-product-explorer-components-products-display--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-product-explorer-components-product-detail--default&args=&globals=locale:en&viewMode=story
      product-explorer-it-infra:
        - /iframe.html?id=widgets-product-explorer-it-infra-components--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-product-explorer-it-infra-components-products-display--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-product-explorer-it-infra-components-product-detail--default&args=&globals=locale:en&viewMode=story
      product-explorer-security:
        - /iframe.html?id=widgets-product-explorer-security-components--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-product-explorer-security-components-product-detail--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-product-explorer-security-components-products-display--default&args=&globals=locale:en&viewMode=story
      solutions-explorer-it-infra:
        - /iframe.html?id=widgets-solutions-explorer-it-infra-components--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-solutions-explorer-it-infra-components-products-display--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-solutions-explorer-it-infra-components-product-detail--default&args=&globals=locale:en&viewMode=story
      trust-radius:
        - /iframe.html?id=widgets-trust-radius-components--default&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-trust-radius-components--gray&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-trust-radius-components--dark&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-trust-radius-components--two-columns&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-trust-radius-components--one-column&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-trust-radius-components--failed-request&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-trust-radius-components--loading&args=&globals=locale:en&viewMode=story
        - /iframe.html?id=widgets-trust-radius-components--multi-product&args=&globals=locale:en&viewMode=story

  drupal:
    image: q0rban/tugboat-drupal:9.4
    expose: 80
    http: false
    depends: mysql
    checkout: true
    urls:
      - /admin/content/interactive-components/widget-instance/1
      - /admin/content/interactive-components/widget-instance/2
      - /admin/content/interactive-components/widget-instance/3
      - /admin/content/interactive-components/widget-instance/4
      - /admin/content/interactive-components/widget-instance/5
      - /admin/content/interactive-components/widget-instance/6
    screenshot:
      enabled: true
      waitUntil:
        - networkidle0

    lighthouse:
      enabled: false

    visualdiff:
      enabled: true

    commands:
      init: |
        set -eux
        curl -sL https://deb.nodesource.com/setup_16.x | sh
        apt-get install -y nodejs
        npm install --global yarn @js-widgets/webpack-cli
        # This is an environment variable we added in the Dockerfile that
        # provides the path to Drupal composer root (not the web root).
        cd $DRUPAL_COMPOSER_ROOT
        composer require drupal/widget_type drupal/widget_instance drupal/widget_ingestion drupal/devel
        # Install Drupal on the site.
        vendor/bin/drush \
          --yes \
          --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat \
          --site-name=Widgets \
          --account-name=ibmadmin \
          --account-pass=${ADMIN_PASSWORD} \
          site:install standard
        # Enable the modules.
        vendor/bin/drush --yes pm:enable widget_type widget_instance widget_ingestion dblog devel
        vendor/bin/drush --yes theme:enable claro olivero
        # Set the Claro theme as default admin theme.
        vendor/bin/drush --yes config-set system.theme admin claro
        vendor/bin/drush --yes config-set system.theme default olivero
        # Rebuild cache.
        vendor/bin/drush cache:rebuild
      build: ./.tugboat/scripts/build-drupal-preview.sh
      online:
        - ${DRUPAL_COMPOSER_ROOT}/vendor/bin/drush --yes --root $DRUPAL_DOCROOT widget_ingestion:ingest --force-ingestion
        - ${DRUPAL_COMPOSER_ROOT}/vendor/bin/drush --yes --root $DRUPAL_DOCROOT php:script "${TUGBOAT_ROOT}/.tugboat/scripts/default-widget-instances.php"
        - ${DRUPAL_COMPOSER_ROOT}/vendor/bin/drush --yes --root $DRUPAL_DOCROOT role:perm:add anonymous 'view widget instance'
