services:
  apache:
    image: tugboatqa/httpd
    commands:
      init:
        - curl -sL https://deb.nodesource.com/setup_16.x | sh
        - apt-get install -y nodejs
        - npm install --global yarn
        - mkdir "${TUGBOAT_ROOT}/docroot"
        - ln -snf "${TUGBOAT_ROOT}/docroot/www" "${DOCROOT}"
        - ln -snf "${TUGBOAT_ROOT}/www" "${TUGBOAT_ROOT}/docroot/www"
      update:
        - yarn install
      build:
        - yarn build-storybook
        - rm -rf "${TUGBOAT_ROOT}/docroot/storybook-static"
        - cp -r storybook-static "${TUGBOAT_ROOT}/docroot"
        - git checkout storybook-static

    lighthouse:
      enabled: false

    screenshot:
      waitUntil:
        - networkidle0

    visualdiff:
      waitUntil:
        - networkidle0

    urls: { }
